### ISSUE TITLE
Thread found: Trojan:Script/Wacatac.B!ml

### ISSUE THREAD

**Issue by sunta3iouxos** [builtbybel/Debloos#3]
As soon as I downloaded the file and tryed to extract it I got this warning. File locked.

**Comment by akgis32** [comment]
same here, didnt had this issue with thisiswin11

**Comment by ed-br** [comment]
for sure a false positive 
clean here https://www.virustotal.com/gui/file/f08564a0fac9b0ab70ced5aa71e64566dff83e6d5f87b7ee4939e1b5e9dbceab

**Comment by Belim** [comment]
@ed-br  yeah
